version: '3.8'

services:
  website:
    build: .
    ports:
      - "80:80"
    container_name: sample-website
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - website-network

networks:
  website-network:
    driver: bridge

volumes:
  logs:
